name: macteo
description: Blogging about stuffs
meta_description: "MacTeo, Blogging about stuffs"

aboutPage: true

markdown: redcarpet
highlighter: pygments

paginate: 20
baseurl: /
domain_name: 'http://macteo.it'
google_analytics: 'UA-67703523-1'
disqus: false
disqus_shortname: 'macteo'

tag_page_layout: tag_page
tag_page_dir: tag

# Details for the RSS feed generator
url:            'http://macteo.it'
author:         'Matteo Gavagnin'
authorTwitter:  'macteo'

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
